SELECT RA.RENTALAGENCYNAME, VINNUMBER, MAKE, MODEL, MILEAGE, VEHICLESTATUSDESC FROM VEHICLE V
LEFT JOIN RENTALAGENCY RA ON RA.RENTALAGENCYID = V.VEHICLEOWNINGAGENCYID
LEFT JOIN VEHICLESTATUS VS ON VS.VEHICLESTATUSID = V.VEHICLESTATUSID
WHERE MILEAGE BETWEEN 10000 AND 35000
ORDER BY RA.RENTALAGENCYNAME;

SELECT CUS.CUSTOMERID, FIRSTNAME ||' '|| LASTNAME "FULL NAME", CUS.ADDRESSLINE1 ||' '||CUS.CITY|| ' ' || CUS.STATECODE || ' ' || CUS.ZIPCODE ||' ' || CUS.COUNTRY AS "Mailing Address", CUS.PHONE, CUS.EMAIL, RA.RENTALAGENCYNAME, COUNT(RA.RENTALAGENCYNAME) AS "# OF TIMES RENTED FROM" FROM CUSTOMER CUS
RIGHT JOIN RENTAL ON RENTAL.CUSTOMERID = CUS.CUSTOMERID
LEFT JOIN RENTALAGENCY RA ON RA.RENTALAGENCYID = RENTAL.RENTALAGENCYID
WHERE CUS.CUSTOMERTYPE = 'R'
GROUP BY CUS.CUSTOMERID, RA.RENTALAGENCYID, FIRSTNAME ||' '|| LASTNAME, CUS.ADDRESSLINE1 ||' '||CUS.CITY|| ' ' || CUS.STATECODE || ' ' || CUS.ZIPCODE ||' ' || CUS.COUNTRY, CUS.PHONE, 
CUS.EMAIL, RA.RENTALAGENCYNAME
ORDER BY COUNT(RA.RENTALAGENCYNAME) DESC; 

SELECT  FIRSTNAME ||' '|| LASTNAME "FULL NAME", CUS.ADDRESSLINE1 ||' '||CUS.CITY|| ' ' || CUS.STATECODE || ' ' || CUS.ZIPCODE ||' ' || CUS.COUNTRY AS "Mailing Address", CUS.PHONE, CUS.EMAIL,
MIN(RENTAL.RENTALPICKUPDATE) "First Rental Date", count(*) "Total Cars Rented" ,ADD_MONTHS(MIN(RENTAL.RENTALPICKUPDATE) , 4) "4 Month Span" FROM RENTAL 
LEFT JOIN CUSTOMER CUS ON CUS.CUSTOMERID = RENTAL.CUSTOMERID
GROUP BY CUS.CUSTOMERID, FIRSTNAME ||' '|| LASTNAME, CUS.ADDRESSLINE1 ||' '||CUS.CITY|| ' ' || CUS.STATECODE || ' ' || CUS.ZIPCODE ||' ' || CUS.COUNTRY, CUS.PHONE, CUS.EMAIL
HAVING COUNT(*) >= 3
ORDER BY CUS.CUSTOMERID;

SELECT RA.RENTALAGENCYNAME, SUM(RENTAL.RENTALDEPOSIT + RIO.INSURANCEOPTIONADDITIONALCOST + (VRC.CATEGORYDAILYRENTALRATE * ABS((RENTAL.RENTALPICKUPDATE - RENTAL.RENTALDROPOFFDATE)))) AS "GENERATED REVENUE", MIN(RENTAL.RENTALPICKUPDATE)||' THROUGH '|| MAX(RENTAL.RENTALPICKUPDATE) AS "TIMESPAN" FROM RENTAL
LEFT JOIN RENTALAGENCY RA ON RA.RENTALAGENCYID = RENTAL.RENTALAGENCYID
LEFT JOIN VEHICLE V ON V.VEHICLEID = RENTAL.VEHICLEID
LEFT JOIN VEHICLERENTALCATEGORY VRC ON VRC.VEHICLERENTALCATEGORYID = V.VEHICLERENTALCATEGORYID
LEFT JOIN RENTALINSURANCEOPTION RIO ON RIO.INSURANCEOPTIONID = RENTAL.INSURANCEOPTIONID
GROUP BY RA.RENTALAGENCYNAME
ORDER BY "GENERATED REVENUE" DESC;

SELECT VINNUMBER, MAKE, MODEL, AVG(RENTALDEPOSIT) "AVERAGE RENTAL DEPOSIT", COUNT(*) "# OF TIMES RENTED" FROM VEHICLE V
LEFT JOIN RENTAL ON RENTAL.VEHICLEID = V.VEHICLEID
GROUP BY V.VEHICLEID, MAKE, MODEL, VINNUMBER
HAVING AVG(RENTALDEPOSIT) IS NOT NULL
ORDER BY "# OF TIMES RENTED" DESC, AVG(RENTALDEPOSIT) DESC;

